Endpoints generator WIP
dwyl/abase pull request #37
Opened 2016-09-26 11:23 UTC by SimonLab

This PR allow us to open the discussion on how we should implement the abase plugin, please read the last section (first version).

@nelsonic @jrans @eliascodes @shouston3 comments and issues are more than welcome!

2016-09-26 12:39 UTC, jrans requested changes
small review for now

2016-09-26 12:39 UTC, jrans commented on package.json
> +    "coverage": "node_modules/.bin/istanbul cover ./node_modules/tape/bin/tape ./test/*.test.js && istanbul check-coverage --statements 100 --functions 100 --lines 100 --branches 100"
why remove the istanbul.yml and replace with something hard to read in the package.json without a target folder for coverage i.e. `src/`. Having a file for the config is much clearer and make adding options and understanding them more helpful than command line configuration? @nelsonic you think otherise?

2016-09-26 12:39 UTC, jrans commented on lib/helpers/user/create_user.js
> +  fs.writeFileSync(path.join(__dirname, '../../../users.json'), JSON.stringify(users));
if this is occurring then `users.json` should be added to gitignore

2016-09-26 12:39 UTC, jrans commented on lib/helpers/configuration/configuration.js
> +      fs.writeFileSync(path.join(__dirname, '../../fields.json'), JSON.stringify(existingFields), 'utf8');
'../../fields.json' should be added to .gitignore for now?

2016-09-26 12:39 UTC, jrans commented on example_config_2.json
> +            "name": "age",
@SimonLab as discussed `name` can be removed and field property should be the unique field identifier, which can infer its type from fields.json object

2016-09-26 12:39 UTC, jrans commented on README.md
> +
👍

2016-09-26 12:39 UTC, jrans commented on example/server.js
> +  server.register([home, {register: abase, options: require('../example_config_2.json')}], function (err) {
requires should be at the top?

2016-09-28 09:00 UTC, shouston3 commented
Closed as too large of a pr, working from pr #41

2016-09-28 09:00 UTC, closed without merging