[WIP] Joi creation
dwyl/abase pull request #48
Opened 2016-09-28 10:57 UTC by jrans

- [ ] Document

Merge after #31

2016-09-28 17:45 UTC, eliasmalik requested changes

2016-09-28 17:45 UTC, eliasmalik commented on test/config_validator.test.js
> +  t.throws(
duplicate assertion?

2016-09-28 18:59 UTC, jrans commented on test/config_validator.test.js
> +  t.throws(
ahh the problem with copy and paste

2016-09-28 19:55 UTC, eliasmalik approved these changes

2016-09-29 09:44 UTC, nelsonic commented
@jrans would you mind rebasing this branch on `master` to reduce the _diff_ for review? (_please/thanks_!)

2016-09-29 09:54 UTC, jrans commented
@nelsonic Of course! Did it before I even saw the comment ;)

2016-09-29 12:02 UTC, nelsonic commented
Thanks @jrans 🎉 
![applause](http://gifrific.com/wp-content/uploads/2013/04/Jose-Mourinho-Applause.gif)

2016-09-29 12:02 UTC, merged